export const FETCH_TOP_TRACKS = "FETCH_TOP_TRACKS";
export const FETCH_TRACKS_FAIL = "FETCH_TRACKS_FAIL";
export const FETCH_LYRICS_BY_TRACK_NAME = "FETCH_LYRICS_BY_TRACK_NAME";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_LYRIC = "FETCH_LYRIC";
